[Node]
Port = "9999"
Seed = "seed"
MaximumExpectedPeerCount = 16
ThresholdMinConnectedPeers = 0

[KadDhtPeerDiscovery]
Enabled = true
RefreshIntervalInSec = 10
ProtocolID = "/erd/kad/sandbox"
InitialPeerList = []
BucketSize = 100
RoutingTableRefreshIntervalInSec = 300

[Sharding]
TargetPeerCount = 0
MaxIntraShard = 0
MaxCrossShard = 0
Type = "NilListSharder"
