[package]
name = "non-fungible-tokens"
version = "0.0.1"
authors = [ "dorin-iancu <dorin.iancu@elrond.com>","hhoareau@gmail.com"]
edition = "2018"
publish=false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [ "elrond-wasm-node",]

[dependencies.elrond-wasm]
version = "0.11.0"

[dependencies.elrond-wasm-derive]
version = "0.11.0"

[dependencies.elrond-wasm-node]
version = "0.11.0"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.11.0"


