[GeneralSettings]
StatusPollingIntervalSec = 2
MaxComputableRounds = 100
StartInEpochEnabled = true
SCDeployEnableEpoch = 0
BuiltInFunctionsEnableEpoch = 0
RelayedTransactionsEnableEpoch = 0
PenalizedTooMuchGasEnableEpoch = 0
SwitchJailWaitingEnableEpoch = 0
BelowSignedThresholdEnableEpoch = 2
SwitchHysteresisForMinNodesEnableEpoch = 2
GenesisString = "67656E65736973"

[Versions]
DefaultVersion = "default"
[[Versions.VersionsByEpochs]]
StartEpoch = 0
Version = "*"

[StoragePruning]
Enabled = true
CleanOldEpochsData = false
NumEpochsToKeep = 4
NumActivePersisters = 3

[EvictionWaitingList]
Size = 10000

[TrieSnapshotDB]
FilePath = "TrieSnapshot"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 40000
MaxOpenFiles = 10

[TrieStorageManagerConfig]
PruningBufferLen = 100000
SnapshotsBufferLen = 1000000
MaxSnapshots = 3

[HeadersPoolConfig]
MaxHeadersPerShard = 1000
NumElementsToRemoveOnEviction = 200

[BadBlocksCache]
Name = "BadBlocksCache"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 3145728

[TxBlockBodyDataPool]
Name = "TxBlockBodyDataPool"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 314572800

[PeerBlockBodyDataPool]
Name = "PeerBlockBodyDataPool"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 314572800

[TxDataPool]
Name = "TxDataPool"
Capacity = 600000
SizePerSender = 20000
SizeInBytes = 419430400
SizeInBytesPerSender = 12288000
Type = "TxCache"
Shards = 16

[TrieNodesDataPool]
Name = "TrieNodesDataPool"
Capacity = 900000
Type = "SizeLRU"
SizeInBytes = 314572800

[WhiteListPool]
Name = "WhiteListPool"
Capacity = 100000
Type = "FIFOSharded"
Shards = 10

[WhiteListerVerifiedTxs]
Name = "WhiteListerVerifiedTxs"
Capacity = 50000
Type = "FIFOSharded"
Shards = 50

[UnsignedTransactionDataPool]
Name = "UnsignedTransactionDataPool"
Capacity = 75000
SizeInBytes = 31457280
Shards = 4

[RewardTransactionDataPool]
Name = "RewardTransactionDataPool"
Capacity = 75000
SizeInBytes = 26214400
Shards = 4

[PublicKeyPeerId]
Name = "PublicKeyPeerId"
Capacity = 30000
Type = "LRU"

[PublicKeyShardId]
Name = "PublicKeyShardId"
Capacity = 30000
Type = "LRU"

[PublicKeyPIDSignature]
Name = "PublicKeyPIDSignature"
Capacity = 3000
Type = "LRU"

[PeerIdShardId]
Name = "PeerIdShardId"
Capacity = 30000
Type = "LRU"

[PeerHonesty]
Name = "PeerHonesty"
Capacity = 5000
Type = "LRU"

[Antiflood]
Enabled = true
NumConcurrentResolverJobs = 50

[Logger]
Path = "logs"
StackTraceDepth = 2

[AddressPubkeyConverter]
Length = 32
Type = "bech32"
SignatureLength = 0

[ValidatorPubkeyConverter]
Length = 96
Type = "hex"
SignatureLength = 48

[Hasher]
Type = "blake2b"

[MultisigHasher]
Type = "blake2b"

[Marshalizer]
Type = "gogo protobuf"
SizeCheckDelta = 10

[VmMarshalizer]
Type = "json"

[TxSignMarshalizer]
Type = "json"

[EpochStartConfig]
MinRoundsBetweenEpochs = 20
RoundsPerEpoch = 200
MinShuffledOutRestartThreshold = 0.05
MaxShuffledOutRestartThreshold = 0.25
MinNumConnectedPeersToStart = 2
MinNumOfPeersToConsiderBlockValid = 2

[ResourceStats]
Enabled = true
RefreshIntervalInSec = 30

[Heartbeat]
MinTimeToWaitBetweenBroadcastsInSec = 20
MaxTimeToWaitBetweenBroadcastsInSec = 25
HeartbeatRefreshIntervalInSec = 60
HideInactiveValidatorIntervalInSec = 3600
DurationToConsiderUnresponsiveInSec = 60

[ValidatorStatistics]
CacheRefreshIntervalInSec = 60

[Consensus]
Type = "bls"

[NTPConfig]
Hosts = [ "time.google.com", "time.cloudflare.com", "time.apple.com",]
Port = 123
TimeoutMilliseconds = 100
SyncPeriodSeconds = 3600
Version = 0

[StateTriesConfig]
CheckpointRoundsModulus = 100
AccountsStatePruningEnabled = true
PeerStatePruningEnabled = true
MaxStateTrieLevelInMemory = 5
MaxPeerTrieLevelInMemory = 5

[BlockSizeThrottleConfig]
MinSizeInBytes = 104857
MaxSizeInBytes = 943718

[Hardfork]
EnableTrigger = true
EnableTriggerFromP2P = true
PublicKeyToListenFrom = "153dae6cb3963260f309959bf285537b77ae16d82e9933147be7827f7394de8dc97d9d9af41e970bc72aecb44b77e819621081658c37f7000d21e2d0e8963df83233407bde9f46369ba4fcd03b57f40b80b06c191a428cfb5c447ec510e79307"
CloseAfterExportInMinutes = 10000
AfterHardFork = false
ImportFolder = "export"
StartRound = 10000
StartNonce = 10000
StartEpoch = 100
GenesisTime = 0
ValidatorGracePeriodInEpochs = 1

[Health]
IntervalVerifyMemoryInSeconds = 5
IntervalDiagnoseComponentsInSeconds = 30
IntervalDiagnoseComponentsDeeplyInSeconds = 120
MemoryUsageToCreateProfiles = 2415919104
NumMemoryUsageRecordsToKeep = 100
FolderPath = "health-records"

[SoftwareVersionConfig]
StableTagLocation = "https://api.github.com/repos/ElrondNetwork/elrond-go/releases/latest"
PollingIntervalInMinutes = 65

[DbLookupExtensions]
Enabled = true

[Logs]
LogFileLifeSpanInSec = 86400

[Versions.Cache]
Name = "VersionsCache"
Capacity = 100
Type = "LRU"

[MiniBlocksStorage.Cache]
Name = "MiniBlocksStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 104857600

[MiniBlocksStorage.DB]
FilePath = "MiniBlocks"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[ReceiptsStorage.Cache]
Name = "ReceiptsStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 10485760

[ReceiptsStorage.DB]
FilePath = "Receipts"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[PeerBlockBodyStorage.Cache]
Name = "PeerBlockBodyStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 104857600

[PeerBlockBodyStorage.DB]
FilePath = "PeerBlocks"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[BlockHeaderStorage.Cache]
Name = "BlockHeaderStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 3145728

[BlockHeaderStorage.DB]
FilePath = "BlockHeaders"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[BootstrapStorage.Cache]
Name = "BootstrapStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 104857600

[BootstrapStorage.DB]
FilePath = "BootstrapData"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[MetaBlockStorage.Cache]
Name = "MetaBlockStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 20971520

[MetaBlockStorage.DB]
FilePath = "MetaBlock"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[TxStorage.Cache]
Name = "TxStorage"
Capacity = 500000
Type = "SizeLRU"
SizeInBytes = 209715200

[TxStorage.DB]
FilePath = "Transactions"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 30000
MaxOpenFiles = 10

[TxLogsStorage.Cache]
Name = "TxLogsStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 20971520

[TxLogsStorage.DB]
FilePath = "Logs"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[UnsignedTransactionStorage.Cache]
Name = "UnsignedTransactionStorage"
Capacity = 250000
Type = "SizeLRU"
SizeInBytes = 104857600

[UnsignedTransactionStorage.DB]
FilePath = "UnsignedTransactions"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 20000
MaxOpenFiles = 10

[RewardTxStorage.Cache]
Name = "RewardTxStorage"
Capacity = 75000
Type = "SizeLRU"
SizeInBytes = 52428800

[RewardTxStorage.DB]
FilePath = "RewardTransactions"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 20000
MaxOpenFiles = 10

[StatusMetricsStorage.Cache]
Name = "StatusMetricsStorage"
Capacity = 1000
Type = "LRU"

[StatusMetricsStorage.DB]
FilePath = "StatusMetricsStorageDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[ShardHdrNonceHashStorage.Cache]
Name = "ShardHdrNonceHashStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 3145728

[ShardHdrNonceHashStorage.DB]
FilePath = "ShardHdrHashNonce"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[MetaHdrNonceHashStorage.Cache]
Name = "MetaHdrNonceHashStorage"
Capacity = 1000
Type = "SizeLRU"
SizeInBytes = 3145728

[MetaHdrNonceHashStorage.DB]
FilePath = "MetaHdrHashNonce"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[AccountsTrieStorage.Cache]
Name = "AccountsTrieStorage"
Capacity = 500000
Type = "SizeLRU"
SizeInBytes = 314572800

[AccountsTrieStorage.DB]
FilePath = "AccountsTrie/MainDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 45000
MaxOpenFiles = 10

[EvictionWaitingList.DB]
FilePath = "EvictionWaitingList"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 100
MaxOpenFiles = 10

[PeerAccountsTrieStorage.Cache]
Name = "PeerAccountsTrieStorage"
Capacity = 5000
Type = "SizeLRU"
SizeInBytes = 104857600

[PeerAccountsTrieStorage.DB]
FilePath = "PeerAccountsTrie/MainDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 1000
MaxOpenFiles = 10

[Antiflood.FastReacting]
IntervalInSeconds = 1
ReservedPercent = 20.0

[Antiflood.SlowReacting]
IntervalInSeconds = 30
ReservedPercent = 20.0

[Antiflood.OutOfSpecs]
IntervalInSeconds = 1
ReservedPercent = 0.0

[Antiflood.PeerMaxOutput]
BaseMessagesPerInterval = 75
TotalSizePerInterval = 2097152

[Antiflood.Cache]
Name = "Antiflood"
Capacity = 7000
Type = "LRU"

[Antiflood.Topic]
DefaultMaxMessagesPerSec = 15000
[[Antiflood.Topic.MaxMessages]]
Topic = "heartbeat"
NumMessagesPerSec = 30

[[Antiflood.Topic.MaxMessages]]
Topic = "shardBlocks*"
NumMessagesPerSec = 30

[[Antiflood.Topic.MaxMessages]]
Topic = "metachainBlocks"
NumMessagesPerSec = 30

[Antiflood.WebServer]
SimultaneousRequests = 100
SameSourceRequests = 10000
SameSourceResetIntervalInSec = 1
[[Antiflood.WebServer.EndpointsThrottlers]]
Endpoint = "/transaction/:hash"
MaxNumGoRoutines = 10

[[Antiflood.WebServer.EndpointsThrottlers]]
Endpoint = "/transaction/send"
MaxNumGoRoutines = 2

[[Antiflood.WebServer.EndpointsThrottlers]]
Endpoint = "/transaction/simulate"
MaxNumGoRoutines = 1

[[Antiflood.WebServer.EndpointsThrottlers]]
Endpoint = "/transaction/send-multiple"
MaxNumGoRoutines = 2

[Antiflood.TxAccumulator]
MaxAllowedTimeInMilliseconds = 250
MaxDeviationTimeInMilliseconds = 25

[VirtualMachine.Execution]
OutOfProcessEnabled = true
WarmInstanceEnabled = false

[VirtualMachine.Querying]
OutOfProcessEnabled = false
WarmInstanceEnabled = true

[Debug.InterceptorResolver]
Enabled = true
CacheSize = 10000
EnablePrint = true
IntervalAutoPrintInSeconds = 20
NumRequestsThreshold = 9
NumResolveFailureThreshold = 3
DebugLineExpiration = 10

[Debug.Antiflood]
Enabled = true
CacheSize = 10000
IntervalAutoPrintInSeconds = 20

[Antiflood.FastReacting.PeerMaxInput]
BaseMessagesPerInterval = 140
TotalSizePerInterval = 4194304

[Antiflood.FastReacting.BlackList]
ThresholdNumMessagesPerInterval = 1000
ThresholdSizePerInterval = 8388608
NumFloodingRounds = 10
PeerBanDurationInSeconds = 300

[Antiflood.SlowReacting.PeerMaxInput]
BaseMessagesPerInterval = 6000
TotalSizePerInterval = 18874368

[Antiflood.SlowReacting.BlackList]
ThresholdNumMessagesPerInterval = 10000
ThresholdSizePerInterval = 37748736
NumFloodingRounds = 2
PeerBanDurationInSeconds = 3600

[Antiflood.OutOfSpecs.PeerMaxInput]
BaseMessagesPerInterval = 2000
TotalSizePerInterval = 10485760

[Antiflood.OutOfSpecs.BlackList]
ThresholdNumMessagesPerInterval = 3600
ThresholdSizePerInterval = 12582912
NumFloodingRounds = 2
PeerBanDurationInSeconds = 3600

[Heartbeat.HeartbeatStorage.Cache]
Name = "HeartbeatStorage"
Capacity = 1000
Type = "LRU"

[Heartbeat.HeartbeatStorage.DB]
FilePath = "HeartbeatStorage"
Type = "LvlDBSerial"
BatchDelaySeconds = 5
MaxBatchSize = 100
MaxOpenFiles = 10

[VirtualMachine.Execution.OutOfProcessConfig]
LogsMarshalizer = "json"
MessagesMarshalizer = "json"
MaxLoopTime = 1000

[Hardfork.ExportStateStorageConfig.Cache]
Name = "HardFork.ExportStateStorageConfig"
Capacity = 5000
Type = "LRU"

[Hardfork.ExportStateStorageConfig.DB]
FilePath = "ExportStateStorage/MainDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 1000
MaxOpenFiles = 10

[Hardfork.ExportKeysStorageConfig.Cache]
Name = "HardFork.ExportKeysStorageConfig"
Capacity = 5000
Type = "LRU"

[Hardfork.ExportKeysStorageConfig.DB]
FilePath = "ExportKeysStorageConfig/MainDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 1000
MaxOpenFiles = 10

[Hardfork.ExportTriesStorageConfig.Cache]
Name = "HardFork.ExportTriesStorageConfig"
Capacity = 5000
Type = "LRU"

[Hardfork.ExportTriesStorageConfig.DB]
FilePath = "ExportTrieStorage/MainTrie"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 1000
MaxOpenFiles = 10

[Hardfork.ImportStateStorageConfig.Cache]
Name = "HardFork.ImportStateStorageConfig"
Capacity = 5000
Type = "LRU"

[Hardfork.ImportStateStorageConfig.DB]
FilePath = "ExportStateStorage/MainDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 1000
MaxOpenFiles = 10

[Hardfork.ImportKeysStorageConfig.Cache]
Name = "HardFork.ImportKeysStorageConfig"
Capacity = 5000
Type = "LRU"

[Hardfork.ImportKeysStorageConfig.DB]
FilePath = "ExportKeysStorageConfig/MainDB"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 1000
MaxOpenFiles = 10

[DbLookupExtensions.MiniblocksMetadataStorageConfig.Cache]
Name = "DbLookupExtensions.MiniblocksMetadataStorage"
Capacity = 20000
Type = "LRU"

[DbLookupExtensions.MiniblocksMetadataStorageConfig.DB]
FilePath = "DbLookupExtensions/MiniblocksMetadata"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 20000
MaxOpenFiles = 10

[DbLookupExtensions.MiniblockHashByTxHashStorageConfig.Cache]
Name = "DbLookupExtensions.MiniblockHashByTxHashStorage"
Capacity = 20000
Type = "LRU"

[DbLookupExtensions.MiniblockHashByTxHashStorageConfig.DB]
FilePath = "DbLookupExtensions_MiniblockHashByTxHash"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 20000
MaxOpenFiles = 10

[DbLookupExtensions.EpochByHashStorageConfig.Cache]
Name = "DbLookupExtensions.EpochByHashStorage"
Capacity = 20000
Type = "LRU"

[DbLookupExtensions.EpochByHashStorageConfig.DB]
FilePath = "DbLookupExtensions_EpochByHash"
Type = "LvlDBSerial"
BatchDelaySeconds = 2
MaxBatchSize = 20000
MaxOpenFiles = 10

[Antiflood.FastReacting.PeerMaxInput.IncreaseFactor]
Threshold = 10
Factor = 1.0

[Antiflood.SlowReacting.PeerMaxInput.IncreaseFactor]
Threshold = 10
Factor = 0.0

[Antiflood.OutOfSpecs.PeerMaxInput.IncreaseFactor]
Threshold = 0
Factor = 0.0
